kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: efs-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: efs-plugin
          volumeMounts:
            - name: efs-utils-config
              mountPath: /etc/amazon/efs
      volumes:
        - name: efs-utils-config
          hostPath:
            path: /etc/amazon/efs
            type: DirectoryOrCreate


